config/routes.rb
Wow::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'characters#index'

  resources :characters, only: [:index, :show, :new, :create]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/character.rb
class Character < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.create(params.require(:character).permit(:name))
    if @character.valid?
      redirect_to "/characters/#{@character.id}"
    else
      render :new
    end
  end

  def show
    @character = Character.find(params[:id])
  end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  def index
    @zombies = Zombie.all
  end

  def show
    @zombie = Zombie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/index.html.erb
<% @characters.each do |character| %>
    <div class="character">
      <%= link_to character.name, character %>
    </div>
<% end %>

<a href="/characters/new">Create New Character ...</a>

app/views/characters/new.html.erb
<%= simple_form_for @character do |f| %>
    <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.submit %>
<% end %>

app/views/characters/show.html.erb
<h1><%= @character.name %></h1>

<%= link_to t("views.characters.index"), characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zombies/index.html.erb
<h1>Zombies available</h1>

<ul>
  <% @zombies.each do |zombie| %>
    <li><%= link_to zombie.name, zombie %></li>
  <% end %>
</ul>

app/views/zombies/show.html.erb
<h1><%= @zombie.name %></h1>

<%= link_to "Back to list ...", zombies_path %>